2024-09-29 at 18:38:26 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:38:26 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-29 at 18:38:26 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-29 at 18:38:26 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-29 at 18:38:30 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-29 at 18:38:32 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-29 at 18:38:35 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 401: {"error":"This method requires an authenticated user"}
2024-09-29 at 18:38:35 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-29 at 18:38:35 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-29 at 18:38:35 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-29 at 18:38:48 CEST WARN  org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl - RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataWriter is already registered.  2nd registration is being ignored.
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-29 at 18:39:05 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-29 at 18:39:06 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 422: {"errors":[{"error_code":"RECORD_INVALID","error_message":"Text can't be blank","error_field":null}],"error_message":"Text can't be blank","error_code":"RECORD_INVALID","error":"Text can't be blank"}
2024-09-29 at 18:39:06 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:39:06 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:39:06 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:39:06 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:39:07 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:07 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-29 at 18:39:07 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-29 at 18:39:07 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-29 at 18:39:08 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:08 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-29 at 18:39:08 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-29 at 18:39:08 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-29 at 18:39:10 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-29 at 18:39:11 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:39:11 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:39:11 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:39:11 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:40:56 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:40:56 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-29 at 18:40:56 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-29 at 18:40:56 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-29 at 18:40:58 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:40:58 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-29 at 18:40:58 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-29 at 18:40:58 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-29 at 18:40:59 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-29 at 18:41:00 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-29 at 18:41:03 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 401: {"error":"This method requires an authenticated user"}
2024-09-29 at 18:41:03 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-29 at 18:41:03 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-29 at 18:41:03 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-29 at 18:41:15 CEST WARN  org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl - RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataWriter is already registered.  2nd registration is being ignored.
2024-09-29 at 18:41:31 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:31 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:41:31 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:41:31 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:41:32 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:32 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-29 at 18:41:32 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-29 at 18:41:32 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-29 at 18:41:33 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 422: {"errors":[{"error_code":"RECORD_INVALID","error_message":"Text can't be blank","error_field":null}],"error_message":"Text can't be blank","error_code":"RECORD_INVALID","error":"Text can't be blank"}
2024-09-29 at 18:41:33 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:41:33 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:41:33 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:41:33 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-29 at 18:41:34 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-29 at 18:41:37 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-29 at 18:41:38 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
